version: "3.1"
services:
  postgresql:
    image: postgres:latest
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 142924d0
      POSTGRES_DB: projetoepi  # Nome do banco de dados a ser criado
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
