# Generated by Django 5.0.6 on 2024-07-07 19:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GTO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'GTO',
                'verbose_name_plural': 'GTO',
            },
        ),
        migrations.AddField(
            model_name='users',
            name='cob',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='date_include',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='users',
            name='docdesignmotresg',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='docdesignnicnarc',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='motoresg',
            field=models.CharField(blank=True, choices=[('S', 'Sim'), ('N', 'Nao')], default='S', max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='nifnarc',
            field=models.CharField(choices=[('NI', 'Nic'), ('NA', 'Narc')], default='NI', max_length=3),
        ),
        migrations.AddField(
            model_name='users',
            name='numbm',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='postgrad',
            field=models.CharField(blank=True, choices=[('sd2cl', 'Sd 2ª Classe BM'), ('sd', 'Sd BM'), ('cb', 'Cb BM'), ('3sgt', '3º Sgt BM'), ('2sgt', '2º Sgt BM'), ('1sgt', '1º Sgt BM'), ('subten', 'Sub Ten BM'), ('2ten', '2º Ten BM'), ('1ten', '1º Ten BM'), ('cap', 'Cap BM'), ('maj', 'Maj BM'), ('tencel', 'Ten Cel BM'), ('cel', 'Cel BM')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='priorit',
            field=models.CharField(blank=True, choices=[('A', 'Alta'), ('M', 'Media'), ('B', 'Baixa')], default='B', max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='sitfunc',
            field=models.CharField(choices=[('A', 'Ativo'), ('I', 'Inativo')], default='AG', max_length=2),
        ),
        migrations.AddField(
            model_name='users',
            name='status',
            field=models.CharField(choices=[('A', 'Ativo'), ('I', 'Inativo')], default='A', max_length=1),
        ),
        migrations.AddField(
            model_name='users',
            name='time_service_days',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='unid_lot',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='unid_princ',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='gto',
            field=models.ManyToManyField(blank=True, related_name='gto', to='usuarios.gto'),
        ),
    ]
