# Generated by Django 5.0.6 on 2024-07-18 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_alter_users_date_include'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='emailfunc',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='sexo',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], default='M', max_length=1),
        ),
    ]
