# Generated by Django 5.0.6 on 2024-07-18 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_users_emailfunc_users_sexo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='date_include',
            field=models.DateField(blank=True, null=True),
        ),
    ]
