# Generated by Django 5.0.6 on 2024-07-18 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_alter_users_date_include'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='unid_princ',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
