# Generated by Django 5.0.6 on 2024-08-20 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0008_users_balaclava_users_capacete_users_conjunto_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='docdesignmotresg',
        ),
        migrations.RemoveField(
            model_name='users',
            name='docdesignnicnarc',
        ),
        migrations.RemoveField(
            model_name='users',
            name='motoresg',
        ),
        migrations.RemoveField(
            model_name='users',
            name='nifnarc',
        ),
        migrations.AddField(
            model_name='users',
            name='ativ_esp',
            field=models.CharField(choices=[('S', 'Sim'), ('N', 'Nao')], default='N', max_length=1),
        ),
        migrations.AddField(
            model_name='users',
            name='list_ativ_esp',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
