# Generated by Django 5.0.6 on 2024-08-20 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0009_remove_users_docdesignmotresg_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='ativ_esp',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
