# Generated by Django 5.0.6 on 2024-08-20 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0010_alter_users_ativ_esp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='ativ_esp',
            field=models.CharField(choices=[('S', 'Sim'), ('N', 'Nao')], default='N', max_length=1),
        ),
    ]
