# Generated by Django 5.0.6 on 2024-08-20 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0011_alter_users_ativ_esp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='gto',
        ),
        migrations.AlterField(
            model_name='users',
            name='list_ativ_esp',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='gto',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
