# Generated by Django 5.0.6 on 2024-08-20 20:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epis', '0002_balaclavaepi_botaepi_capaceteaquaticoepi_capaceteepi_and_more'),
        ('usuarios', '0012_remove_users_gto_alter_users_list_ativ_esp_users_gto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='balaclava',
        ),
        migrations.RemoveField(
            model_name='users',
            name='capacete',
        ),
        migrations.RemoveField(
            model_name='users',
            name='conjunto',
        ),
        migrations.RemoveField(
            model_name='users',
            name='luva',
        ),
        migrations.AddField(
            model_name='users',
            name='ciurb_balaclava',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ciurb_balaclava', to='epis.balaclavaepi'),
        ),
        migrations.AddField(
            model_name='users',
            name='ciurb_bota',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ciurb_bota', to='epis.botaepi'),
        ),
        migrations.AddField(
            model_name='users',
            name='ciurb_capacete',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ciurb_capacete', to='epis.capaceteepi'),
        ),
        migrations.AddField(
            model_name='users',
            name='ciurb_conjunto',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ciurb_conjunto', to='epis.conjuntoepi'),
        ),
        migrations.AddField(
            model_name='users',
            name='ciurb_luva',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ciurb_luva', to='epis.luvaepi'),
        ),
        migrations.AddField(
            model_name='users',
            name='motresg_bota',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='motresg_bota', to='epis.botaepi'),
        ),
        migrations.AddField(
            model_name='users',
            name='motresg_capacete',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='motresg_capacete', to='epis.capaceteepi'),
        ),
        migrations.AddField(
            model_name='users',
            name='motresg_conjunto',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='motresg_conjunto', to='epis.conjuntoepi'),
        ),
        migrations.AddField(
            model_name='users',
            name='motresg_luva',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='motresg_luva', to='epis.luvaepi'),
        ),
        migrations.AddField(
            model_name='users',
            name='multi_bota',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='multi_bota', to='epis.botaepi'),
        ),
        migrations.AddField(
            model_name='users',
            name='multi_capacete',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='multi_capacete', to='epis.capaceteepi'),
        ),
        migrations.AddField(
            model_name='users',
            name='multi_conjunto',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='multi_conjunto', to='epis.conjuntoepi'),
        ),
        migrations.AddField(
            model_name='users',
            name='multi_luva',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='multi_luva', to='epis.luvaepi'),
        ),
        migrations.AddField(
            model_name='users',
            name='salv_capacete_alt',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salv_capacete_alt', to='epis.capaceteveicularepi'),
        ),
        migrations.AddField(
            model_name='users',
            name='salv_capacete_aqu',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salv_capacete_aqu', to='epis.capaceteaquaticoepi'),
        ),
        migrations.AddField(
            model_name='users',
            name='salv_luva_veic',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salv_luva_veic', to='epis.luvaveicularepi'),
        ),
    ]
