# Generated by Django 5.0.6 on 2024-08-20 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0013_remove_users_balaclava_remove_users_capacete_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GTO',
        ),
    ]
