# Generated by Django 5.0.6 on 2024-09-18 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0014_delete_gto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='sitfunc',
            field=models.CharField(choices=[('1', 'ATIVIDADE MEIO'), ('2', 'ATIVID.FIM NA SEDE'), ('3', 'ATIVID.FIM DESTACADO'), ('4', 'MATRICULADO EM CURSO'), ('5', 'RESERVA NAO REMUNERA'), ('6', 'RES. TEMPO SERVICO'), ('7', 'RES.TEMPO EFET. SERV'), ('8', 'RES.LIMITE IDADE'), ('9', 'RESERVA CARGO ELETIV'), ('10', 'RESERVA CARGO PUBLIC'), ('11', 'REFORMA LIMITE IDADE'), ('12', 'REFORMA INCAP.FISICA'), ('13', 'REFORMA DISCIPLINAR'), ('14', 'EXCLUIDO'), ('15', 'QOR DESIGNADO'), ('16', 'LIC.TRAT.PROP.SAUDE'), ('17', 'LIC.TRAT.PES.FAMILIA'), ('18', 'LIC.INTERESSE PARTIC'), ('19', 'AGREG.FIL.PART.POLIT'), ('20', 'AGREG.EXCEDER QUADRO'), ('21', 'DESERTOR'), ('22', 'AGREG. DISP.ORG.PUBL'), ('23', 'AGREG. EXTRAVIO'), ('24', 'AFAST.AG.TRANSF.INAT'), ('25', 'AG.CARGO PUB.S/VENC.'), ('26', 'AGREG.SUSP.EX.FUNCAO'), ('27', 'AGREG.CUMP SENT PENA'), ('28', 'AG. ELEICAO ANTES 98'), ('29', 'CONDENADO PREST.SERV'), ('30', 'PRESO A DISP JUSTICA'), ('31', 'SUBMETIDO A CJ'), ('32', 'APOSENTADO'), ('33', 'JUIZ / TJM'), ('34', 'F.C.DISP.FUN.PUBLICA'), ('35', 'INAT VENC OUT ORGAOS'), ('36', 'FERIAS'), ('37', 'FC AG. APOSENTADORIA'), ('38', 'LICENCA A GESTANTE'), ('39', 'PERDA DO POSTO/GRAD'), ('40', 'REF.VOLUNT. QOR/QPR'), ('41', 'REF.LIM.IDAD.QOR/QPR'), ('42', 'INAT PRESO/JUSTICA'), ('43', 'F.C.DISP.OUTRO ORGAO'), ('44', 'REFORMA P/ INVALIDEZ'), ('45', 'QPR DESIGNADO'), ('46', 'AG LIC.SAU.SUP 1 ANO'), ('47', 'QUADRO ESPECIALISTA'), ('48', 'CONDENADO/SEM SERVI'), ('49', 'PRESO JUST/SEM SERV'), ('50', 'INATIVA'), ('51', 'ART.12/EC 39/1999'), ('52', 'DISP CAUTELAR'), ('53', 'AG.CARGO PUB.C/VENC.'), ('54', 'PRACA ADIDO.AG.REF'), ('55', 'OFICIAL ADIDO AG REF'), ('56', 'PARCIALMENTE CAPAZ'), ('57', 'INTERD.JUDIC.-ATIVO'), ('58', 'AGR.ELEICAO POS 1998'), ('59', 'AGREGA ENTID. CLASSE'), ('60', 'MAT CURSO FORA CBMMG'), ('61', 'OFICIAL AG. 393 CPPM'), ('62', 'AG.ART.134/L.5301/69'), ('63', 'LIC.MED. NAO HOMOLOG'), ('64', 'AFASTADO JUDIC CBMMG'), ('65', 'REFORMA INTERDIÃO'), ('66', 'EX BM C/PROVENTO JUD'), ('67', 'PESSOAL DA SAUDE'), ('68', 'AGRG. DEC. JUDICIAL'), ('69', 'FUNCIONARIO CIVIL'), ('70', 'FORÇA NACIONAL')], default='2', max_length=2),
        ),
    ]
