# Generated by Django 5.0.6 on 2024-09-18 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0015_alter_users_sitfunc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='unid_lot',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='unid_princ',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
