# Generated by Django 5.0.6 on 2024-09-19 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0016_alter_users_unid_lot_alter_users_unid_princ'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='numbm',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
