# Generated by Django 5.0.6 on 2024-09-25 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0017_alter_users_numbm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='priorit',
            field=models.CharField(blank=True, choices=[('1', '1ª Prioridade'), ('2', '2ª Prioridade'), ('3', '3ª Prioridade'), ('4', '4ª Prioridade')], default='B', max_length=1, null=True),
        ),
    ]
