# Generated by Django 5.0.6 on 2024-07-24 02:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlanoDistribuicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grupo', models.CharField(choices=[('CI', 'Combate a Incêndio'), ('NA', 'Natação'), ('SV', 'Salvamento Veicular')], max_length=2)),
                ('epi', models.CharField(choices=[('CP', 'Capacete'), ('LV', 'Luva'), ('CJ', 'Conjunto'), ('BL', 'Balaclava')], max_length=2)),
                ('data', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Luva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=100)),
                ('modelo', models.CharField(max_length=100)),
                ('ano_de_fabricacao', models.IntegerField()),
                ('estado_de_conservacao', models.CharField(choices=[('OT', 'Ótimo'), ('BO', 'Bom'), ('RA', 'Razoável'), ('RU', 'Ruim')], max_length=2)),
                ('condicao_analisada', models.CharField(choices=[('PR', 'Procede'), ('NP', 'Não procede')], max_length=2)),
                ('data_de_recebimento', models.DateField(blank=True, null=True)),
                ('circunferencia_mao', models.CharField(max_length=50)),
                ('tamanho', models.CharField(max_length=50)),
                ('plano_distribuicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='epis.planodistribuicao')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Conjunto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=100)),
                ('modelo', models.CharField(max_length=100)),
                ('ano_de_fabricacao', models.IntegerField()),
                ('estado_de_conservacao', models.CharField(choices=[('OT', 'Ótimo'), ('BO', 'Bom'), ('RA', 'Razoável'), ('RU', 'Ruim')], max_length=2)),
                ('condicao_analisada', models.CharField(choices=[('PR', 'Procede'), ('NP', 'Não procede')], max_length=2)),
                ('data_de_recebimento', models.DateField(blank=True, null=True)),
                ('jaqueta', models.CharField(max_length=50)),
                ('calca', models.CharField(max_length=50)),
                ('plano_distribuicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='epis.planodistribuicao')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Capacete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=100)),
                ('modelo', models.CharField(max_length=100)),
                ('ano_de_fabricacao', models.IntegerField()),
                ('estado_de_conservacao', models.CharField(choices=[('OT', 'Ótimo'), ('BO', 'Bom'), ('RA', 'Razoável'), ('RU', 'Ruim')], max_length=2)),
                ('condicao_analisada', models.CharField(choices=[('PR', 'Procede'), ('NP', 'Não procede')], max_length=2)),
                ('data_de_recebimento', models.DateField(blank=True, null=True)),
                ('cor', models.CharField(max_length=50)),
                ('plano_distribuicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='epis.planodistribuicao')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Balaclava',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=100)),
                ('modelo', models.CharField(max_length=100)),
                ('ano_de_fabricacao', models.IntegerField()),
                ('estado_de_conservacao', models.CharField(choices=[('OT', 'Ótimo'), ('BO', 'Bom'), ('RA', 'Razoável'), ('RU', 'Ruim')], max_length=2)),
                ('condicao_analisada', models.CharField(choices=[('PR', 'Procede'), ('NP', 'Não procede')], max_length=2)),
                ('data_de_recebimento', models.DateField(blank=True, null=True)),
                ('camadas', models.CharField(choices=[('SI', 'Simples'), ('DU', 'Dupla'), ('TR', 'Tripla')], max_length=2)),
                ('plano_distribuicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='epis.planodistribuicao')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
