# Generated by Django 5.0.6 on 2024-08-20 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BalaclavaEPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('possui', models.BooleanField(default=False)),
                ('estadodeconservacao', models.CharField(choices=[('Ótimo', 'Ótimo'), ('Bom', 'Bom'), ('Razoável', 'Razoável'), ('Ruim', 'Ruim')], max_length=10)),
                ('condicao', models.CharField(choices=[('P', 'Procede'), ('NP', 'Não Procede')], max_length=2)),
                ('marca', models.CharField(max_length=100)),
                ('modelo', models.CharField(max_length=100)),
                ('anofabricacao', models.IntegerField()),
                ('plannumber', models.IntegerField()),
                ('datapreenchimento', models.DateField()),
                ('recebido', models.BooleanField(default=False)),
                ('datarecebimento', models.DateField(blank=True, null=True)),
                ('camadas', models.CharField(choices=[('Simples', 'Simples'), ('Dupla', 'Dupla'), ('Tripla', 'Tripla')], max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BotaEPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('possui', models.BooleanField(default=False)),
                ('estadodeconservacao', models.CharField(choices=[('Ótimo', 'Ótimo'), ('Bom', 'Bom'), ('Razoável', 'Razoável'), ('Ruim', 'Ruim')], max_length=10)),
                ('condicao', models.CharField(choices=[('P', 'Procede'), ('NP', 'Não Procede')], max_length=2)),
                ('marca', models.CharField(max_length=100)),
                ('modelo', models.CharField(max_length=100)),
                ('anofabricacao', models.IntegerField()),
                ('plannumber', models.IntegerField()),
                ('datapreenchimento', models.DateField()),
                ('recebido', models.BooleanField(default=False)),
                ('datarecebimento', models.DateField(blank=True, null=True)),
                ('tamanho', models.IntegerField(choices=[(35, '35'), (36, '36'), (37, '37'), (38, '38'), (39, '39'), (40, '40'), (41, '41'), (42, '42'), (43, '43'), (44, '44'), (45, '45'), (46, '46'), (47, '47'), (48, '48'), (49, '49'), (50, '50')])),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CapaceteAquaticoEPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('possui', models.BooleanField(default=False)),
                ('estadodeconservacao', models.CharField(choices=[('Ótimo', 'Ótimo'), ('Bom', 'Bom'), ('Razoável', 'Razoável'), ('Ruim', 'Ruim')], max_length=10)),
                ('condicao', models.CharField(choices=[('P', 'Procede'), ('NP', 'Não Procede')], max_length=2)),
                ('marca', models.CharField(max_length=100)),
                ('modelo', models.CharField(max_length=100)),
                ('anofabricacao', models.IntegerField()),
                ('plannumber', models.IntegerField()),
                ('datapreenchimento', models.DateField()),
                ('recebido', models.BooleanField(default=False)),
                ('datarecebimento', models.DateField(blank=True, null=True)),
                ('cor', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CapaceteEPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('possui', models.BooleanField(default=False)),
                ('estadodeconservacao', models.CharField(choices=[('Ótimo', 'Ótimo'), ('Bom', 'Bom'), ('Razoável', 'Razoável'), ('Ruim', 'Ruim')], max_length=10)),
                ('condicao', models.CharField(choices=[('P', 'Procede'), ('NP', 'Não Procede')], max_length=2)),
                ('marca', models.CharField(max_length=100)),
                ('modelo', models.CharField(max_length=100)),
                ('anofabricacao', models.IntegerField()),
                ('plannumber', models.IntegerField()),
                ('datapreenchimento', models.DateField()),
                ('recebido', models.BooleanField(default=False)),
                ('datarecebimento', models.DateField(blank=True, null=True)),
                ('cor', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CapaceteVeicularEPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('possui', models.BooleanField(default=False)),
                ('estadodeconservacao', models.CharField(choices=[('Ótimo', 'Ótimo'), ('Bom', 'Bom'), ('Razoável', 'Razoável'), ('Ruim', 'Ruim')], max_length=10)),
                ('condicao', models.CharField(choices=[('P', 'Procede'), ('NP', 'Não Procede')], max_length=2)),
                ('marca', models.CharField(max_length=100)),
                ('modelo', models.CharField(max_length=100)),
                ('anofabricacao', models.IntegerField()),
                ('plannumber', models.IntegerField()),
                ('datapreenchimento', models.DateField()),
                ('recebido', models.BooleanField(default=False)),
                ('datarecebimento', models.DateField(blank=True, null=True)),
                ('cor', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ConjuntoEPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('possui', models.BooleanField(default=False)),
                ('estadodeconservacao', models.CharField(choices=[('Ótimo', 'Ótimo'), ('Bom', 'Bom'), ('Razoável', 'Razoável'), ('Ruim', 'Ruim')], max_length=10)),
                ('condicao', models.CharField(choices=[('P', 'Procede'), ('NP', 'Não Procede')], max_length=2)),
                ('marca', models.CharField(max_length=100)),
                ('modelo', models.CharField(max_length=100)),
                ('anofabricacao', models.IntegerField()),
                ('plannumber', models.IntegerField()),
                ('datapreenchimento', models.DateField()),
                ('recebido', models.BooleanField(default=False)),
                ('datarecebimento', models.DateField(blank=True, null=True)),
                ('jaquetatamanho', models.CharField(choices=[('Pequeno', 'Pequeno'), ('Médio', 'Médio'), ('Grande', 'Grande'), ('1º Extra Grande', '1º Extra Grande'), ('2º Extra Grande', '2º Extra Grande'), ('3º Extra Grande', '3º Extra Grande')], max_length=20)),
                ('jaquetacomplemento', models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4')])),
                ('calcatamanho', models.CharField(choices=[('Pequeno', 'Pequeno'), ('Médio', 'Médio'), ('Grande', 'Grande'), ('1º Extra Grande', '1º Extra Grande'), ('2º Extra Grande', '2º Extra Grande'), ('3º Extra Grande', '3º Extra Grande')], max_length=20)),
                ('calcacomplemento', models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4')])),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LuvaEPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('possui', models.BooleanField(default=False)),
                ('estadodeconservacao', models.CharField(choices=[('Ótimo', 'Ótimo'), ('Bom', 'Bom'), ('Razoável', 'Razoável'), ('Ruim', 'Ruim')], max_length=10)),
                ('condicao', models.CharField(choices=[('P', 'Procede'), ('NP', 'Não Procede')], max_length=2)),
                ('marca', models.CharField(max_length=100)),
                ('modelo', models.CharField(max_length=100)),
                ('anofabricacao', models.IntegerField()),
                ('plannumber', models.IntegerField()),
                ('datapreenchimento', models.DateField()),
                ('recebido', models.BooleanField(default=False)),
                ('datarecebimento', models.DateField(blank=True, null=True)),
                ('circunferenciamao', models.CharField(choices=[('12 a 15 cm', '12 a 15 cm'), ('18 a 19 cm', '18 a 19 cm'), ('19 a 20 cm', '19 a 20 cm'), ('20 a 21,5 cm', '20 a 21,5 cm'), ('21,5 a 23 cm', '21,5 a 23 cm'), ('23 a 25 cm', '23 a 25 cm'), ('25 a 28 cm', '25 a 28 cm'), ('28 a 30 cm', '28 a 30 cm')], max_length=30)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LuvaVeicularEPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('possui', models.BooleanField(default=False)),
                ('estadodeconservacao', models.CharField(choices=[('Ótimo', 'Ótimo'), ('Bom', 'Bom'), ('Razoável', 'Razoável'), ('Ruim', 'Ruim')], max_length=10)),
                ('condicao', models.CharField(choices=[('P', 'Procede'), ('NP', 'Não Procede')], max_length=2)),
                ('marca', models.CharField(max_length=100)),
                ('modelo', models.CharField(max_length=100)),
                ('anofabricacao', models.IntegerField()),
                ('plannumber', models.IntegerField()),
                ('datapreenchimento', models.DateField()),
                ('recebido', models.BooleanField(default=False)),
                ('datarecebimento', models.DateField(blank=True, null=True)),
                ('circunferenciamao', models.CharField(choices=[('12 a 15 cm', '12 a 15 cm'), ('18 a 19 cm', '18 a 19 cm'), ('19 a 20 cm', '19 a 20 cm'), ('20 a 21,5 cm', '20 a 21,5 cm'), ('21,5 a 23 cm', '21,5 a 23 cm'), ('23 a 25 cm', '23 a 25 cm'), ('25 a 28 cm', '25 a 28 cm'), ('28 a 30 cm', '28 a 30 cm')], max_length=30)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='balaclava',
            name='plano_distribuicao',
        ),
        migrations.RemoveField(
            model_name='capacete',
            name='plano_distribuicao',
        ),
        migrations.RemoveField(
            model_name='conjunto',
            name='plano_distribuicao',
        ),
        migrations.RemoveField(
            model_name='luva',
            name='plano_distribuicao',
        ),
    ]
