# Generated by Django 5.0.6 on 2024-08-20 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('epis', '0002_balaclavaepi_botaepi_capaceteaquaticoepi_capaceteepi_and_more'),
        ('usuarios', '0013_remove_users_balaclava_remove_users_capacete_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Balaclava',
        ),
        migrations.DeleteModel(
            name='Capacete',
        ),
        migrations.DeleteModel(
            name='Conjunto',
        ),
        migrations.DeleteModel(
            name='Luva',
        ),
        migrations.DeleteModel(
            name='PlanoDistribuicao',
        ),
    ]
