# Generated by Django 5.0.6 on 2024-09-19 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epis', '0005_alter_balaclavaepi_anofabricacao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balaclavaepi',
            name='plannumber',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='botaepi',
            name='plannumber',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='capaceteaquaticoepi',
            name='plannumber',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='capaceteepi',
            name='plannumber',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='capaceteveicularepi',
            name='plannumber',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='conjuntoepi',
            name='plannumber',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='luvaepi',
            name='plannumber',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='luvaveicularepi',
            name='plannumber',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
